### ISSUE TITLE
Image size issue

### ISSUE THREAD

**Issue by robertnicjoo** [mycurelabs/vue-html-to-paper#45]
Somehow I can't set image size in print preview

![00](https://user-images.githubusercontent.com/8672823/80897934-2c51fb80-8d28-11ea-9a2a-f33771a06c09.PNG)

```css
@media print {
        @page {
            size: A4;
        }
        .el-image img {
            width: 200px !important;
            height: 200px !important;
        }
}
```

Any idea how to set image size?
